config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :pics
  devise_for :users
  
 root "pics#index"

  get "about" => "pages#about"
  get "posts" => "pages#posts"
  get "build" => "pages#build"
  get "home" => "pages#home"
 

end

app/models/pic.rb
class Pic < ActiveRecord::Base
	belongs_to :user

	has_attached_file :image, :styles => { :medium => "1600x1600>", :thumb => "1600x1600>" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pics
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def posts
  end

  def build
  end

  def homes
  end
  


end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_pic, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  

 



  def index
    @pics = Pic.all
  end




  def show
  end

 
  def new
    @pic = current_user.pics.build
  end


  def edit
  end

 
  def create
    @pic = current_user.pics.build(pic_params)
      if @pic.save
        redirect_to @pic, notice: 'Pic was successfully created.'
      else
        render action: 'new'
      end
    end
  end

  def update
      if @pic.update(pic_params)
        redirect_to @pic, notice: 'Pic was successfully updated.'
      else
        render action: 'edit'
      end

 
  def destroy
    @pic.destroy
    redirect_to pics_url
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pic
      @pic = Pic.find(params[:id])
    end

    def correct_user
      @pic = current_user.pics.find_by(id: params[:id])
      redirect_to pics_path, notice: "Not authorized to edit this pic" if @pic.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pic_params
      params.require(:pic).permit(:description, :image)
    end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]


  def index
    @posts = Post.all
  end


  def show
  end

  def new
    @post = Post.new
  end

 
  def edit
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="">
      <%= link_to 'IVLens Home', root_path %>
      </a>
    </div>
    

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %> 
        <li><%= link_to 'Communicate', posts_path %></li>
        <li><%= link_to 'New Post', new_post_path %></li>
        <li><%= link_to 'New Pic', new_pic_path %></li>
        <li><%= link_to "Account Settings", edit_user_registration_path %></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %> </li>
        <% else %>
          <li><%= link_to "IVLens © 2015" %>
          
          <li><%= link_to "Sign Up", new_user_registration_path %>
          <li><%= link_to "About", about_path %>
          <li><%= link_to "Sign in", new_user_session_path %><li>
        <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ivlens</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
			<% content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/_home.html.erb
<div id="wrapper">


<div id="first">
	<div>
  	<h1>Login</h1>
</div>
  

 <div id="second">
    
<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <% if devise_mapping.rememberable? -%>
    <div class="field">
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
    </div>
  <% end -%>
 <div class="form-group">
        <%= f.submit "Sign in", class: "btn btn-primary" %>
      </div>
 
<% end %>

</div>

<div style="position:absolute; left:400px; top:85px;">

		<h1> </span>Welcome to IVLens</h1>
		
    
    
    <p> <span class="glyphicon glyphicon-plus"></span>      View photos from the world around you</p>
		

    <p> <span class="glyphicon glyphicon-plus"></span>      Share with people you know </p>


	
		<p> <span class="glyphicon glyphicon-plus"></span>      Free and easy to navigate</p>

		<p> <span class="glyphicon glyphicon-plus"></span>      a service that anyone can use </p>
	</div>

<div style="position:absolute; left:800px; top: 85px;">

    
    <h1><%= link_to "facebook IVLens", "https://www.facebook.com/pages/IVlens/447343398774475" %></h1>
    <h1><%= link_to "Polaroid", "https://www.polaroid.com" %></h1>
    <h1><%= link_to "Twitter @IVLens", "https://www.twitter.com" %></h1>


</div>

  <div>
    <h1> #IVLens: </h1>
  </div>

	</div>

</div>

app/views/pages/about.html.erb
<div>
  <h1>Express Yourself Using IVLens</h1>
</div>
  	<p>ivlens is a photo sharing and blog web application that is free and easy to use</p>
	<p>Simply sign-up and add photos of your liking, which will be displayed for the world to see </p>

<%= link_to 'Sign up', new_user_registration_path %>

<div>
  <h1>help build IVLens</h1>
</div>

<p> founded at UCSB, IVLens is now expanding to encompass anyone, anywhere </p>
<p> interested in helping develop IVLens? </p>

<p> Send all inquires to ivlensucsb@gmail.com </p>

app/views/pages/home.html.erb
<div id="wrapper">


<div id="first">
	<div>
  	<h1>ivlens</h1>
</div>
  

 <div id="second">
    
<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <% if devise_mapping.rememberable? -%>
    <div class="field">
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
    </div>
  <% end -%>
 <div class="form-group">
        <%= f.submit "Sign in", class: "btn btn-primary" %>
      </div>
 
<% end %>

</div>

<div id="third">


<h2>Sign up</h2>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true  %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @validatable %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off"  %>
  </div>

</div>
 

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>






    

	

	<div>
		<h1> Express yourself</h1>
		<p> View photos from the world around you </p>
		<p> Share with people you know </p>
	</div>

	<div>
		<h1> Free and easy to use</h1>
		<p> a service that anyone can use </p>
	</div>

	

</div>

app/views/pages/posts.html.erb
<h1> Posts </h>

app/views/pics/_form.html.erb
<%= form_for@pic, html: { multipart: true } do |f| %>
  <% if @pic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pic.errors.count, "error") %> prohibited this pic from being saved:</h2>

      <ul>
      <% @pic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pics/edit.html.erb
<h1>Editing Pic</h1>

<%= render 'form' %>

<%= link_to 'Show', @pic %> |
<%= link_to 'Back', pics_path %>

app/views/pics/index.html.erb
<%= render 'pages/home'	unless user_signed_in? %>

<div id="pics" class="transitions-enabled">
  <% @pics.each do |pic| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pic.image.url(:medium)), pic %>
    </div>
  <% end %>
</div>  

app/views/pics/new.html.erb
<h1>New Pic</h1>

<%= render 'form' %>

<%= link_to 'Back', pics_path %>

app/views/pics/show.html.erb
<%= link_to 'Back', pics_path %>

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <%= image_tag @pic.image.url(:medium) %>
      </div>
      <div class="panel-body">
        
        <% if @pic.user == current_user %>
         
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.comment %></td>
   
        
      
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @post.comment %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>